### ISSUE TITLE
Wrong reference to long description of the setuptools

### ISSUE THREAD

**Issue by rexut** [lipro/sphinxcontrib-ansi#3]
Error is:
```
Obtaining file://.../sphinxcontrib-ansi
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File ".../sphinxcontrib-ansi/setup.py", line 29, in <module>
        with open('README') as stream:
    IOError: [Errno 2] No such file or directory: 'README'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in .../sphinxcontrib-ansi/
```

**Comment by rexut** [comment]
This error occurs since the `README` file was renamed with commit 75b3b93fe225fcf7ce09e36ae2885ad6319ccecb
